### ISSUE TITLE
Self-Signed CA

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#12]
_From @Bregor on September 6, 2016 18:13_

At first, thank you for the wonderful app!

It will be perfect if you add a possibility to use self-signed CAs which will grant access to test and development clusters.

Thanks in advance.

_Copied from original issue: skippbox/cabin-issues#13_

**Comment by sebgoa** [comment]
Hi, right now the TLS verification is actually disabled.

What problem are you having exactly ?

**Comment by sebgoa** [comment]
_From @Bregor on September 6, 2016 19:39_

@runseb I have some k8s-clusters for QA needs which are world accessible.
For the authentication, I use tokens and public part of CA.

Clusters looks like following:

```
clusters:
- cluster:
    certificate-authority-data: <ca.pem here>
    server: https://<qa1>:8443
  name: qa1
```

The main problem is with a certificate-authority part. There is no place in **Cabin** to put it in and without CA my clusters reject authentications.
