### ISSUE TITLE
Display charts repository

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#39]
_From @sebgoa on July 12, 2016 10:44_

We should be able to see a list of charts available from a repository.

There should be a default repository configured.
We fetched the `index.yaml` from the repo and construct a grid of sorts to display a catalog of applications.

_Copied from original issue: skippbox/cabin-sw#24_

**Comment by sebgoa** [comment]
A chart repository is available at:
https://console.cloud.google.com/storage/browser/kubernetes-charts-testing/?project=kubernetes-charts

or 

https://console.cloud.google.com/storage/browser/kubernetes-charts/?project=kubernetes-charts

Each repo has a `index.yaml` file that looks like this:

```
alpine-0.1.0:
  name: alpine
  url: http://storage.googleapis.com/kubernetes-charts/alpine-0.1.0.tgz
  created: 2016-06-22 20:08:27.35858224 +0000 UTC
  checksum: 0e6661f193211d7a5206918d42f5c2a9470b737d
  chartfile:
    name: alpine
    home: https://k8s.io/helm
    sources:
    - https://github.com/kubernetes/helm
    version: 0.1.0
    description: Deploy a basic Alpine Linux pod
    keywords: []
    maintainers: []
    engine: ""
```

here it is a single chart.

Unfortunately there is no icon to display, so we might have to create a map ourselves based on the chart name and an icon.
