### ISSUE TITLE
Deploy action for charts

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#40]
_From @sebgoa on July 12, 2016 10:47_

once we know how to use gRPC, we should be able to deploy an application.

From the catalog view (application lists coming from the repository).

A single click on the app should trigger a deploy.

_Copied from original issue: skippbox/cabin-sw#26_

**Comment by sebgoa** [comment]
to deploy a chart we will first need _somehow_ to create a port-forwarding to the pod running Tiller (the server side of Helm).

there is an API to create a port-forwarding (though I never used it):

```
http://kubernetes.io/kubernetes/third_party/swagger-ui/#!/api%2Fv1/connectPostNamespacedPodPortforward
```

Once the port forwarding is in place we should be able to use gRPC _locally_.

**Comment by sebgoa** [comment]
You can see the basic logic in the helm code:

https://github.com/kubernetes/helm/blob/a0bc510662c1a109de6af2cfb062137cbc54fcab/cmd/helm/helm.go

**Comment by sebgoa** [comment]
here is the line that creates the port forward:

https://github.com/kubernetes/helm/blob/ca6151f8607c8ad79fb840ae536c76e69bba6b68/pkg/kube/tunnel.go#L54

but there is more to it. Finding an available local port, tearing down the tunnel etc...

**Comment by sebgoa** [comment]
Once the port forwarding rule is set, you should be able to call `installRelease` over gRPC

client code example:

https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L98

this is implemented server side on `tiller` with:

https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L98

notice that there are other RPC implemented like getting the status of a release or deleting one.

A _release_ is the name given to a chart that is installed on your k8s cluster.

**Comment by sebgoa** [comment]
_From @kemcake on August 3, 2016 9:9_

Port forward creating seems to be tough, it also needs SPDY (even if it's deprecated everywhere).

**Comment by sebgoa** [comment]
you can always create a nodeport service to expose a tiller-rc, and make gRPC tiller requests on that port. But it will be unauthenticated and totally insecure.

I would say that's last resort and only for demo purpose.

so trying to get this port-forward is our only solution for now.

that said, I think helm will need to evolve to expose tiller differently to the outside.

**Comment by sebgoa** [comment]
_From @kemcake on August 5, 2016 9:52_

After a lot of time trying to make SPDY calls working, I can't get it to work with the kubernetes API for now. Still getting a "unexpected end of stream"... Don't really know what to do now excepte search again and again a solution

Btw, it seems like kubernetes wants to switch to HTTP/2 but when... https://github.com/kubernetes/kubernetes/issues/7452

**Comment by sebgoa** [comment]
ok so let's pause on that for now, and work on the react-native web test.

there is also a few items to create a basic deployment and expose a deployment via a service.

**Comment by sebgoa** [comment]
to move on with this we can go the NodePort route.

Start tiller as a deployment and create a service of type NodePort.

Then we can reach the tiller service over the <node_IP>:<NodePort>

without web sockets or SPDY

**Comment by sebgoa** [comment]
ok so currently, tiller can be deployed and we can reach it via a NodePort (insecure).

With [`helm`](https://github.com/kubernetes/helm/releases/tag/v2.0.0-alpha.3)

```
export HELM_HOST=195.19.30.110:30774
./helm list
wobbly-lionfish
```

The deployed chart (name given to apps in the store) is a redis-standalone. We can see the Pod present. I will leave it running.

To test gRPC calls to tiller on iOS, we can simply try to list the releases and see if we can get the same returned value `wobbly-lionfish`.

proto file for a release is here:
https://github.com/kubernetes/helm/blob/master/_proto/hapi/release/release.proto
and here
https://github.com/kubernetes/helm/blob/master/pkg/proto/hapi/release/release.pb.go

and the `listRelease` gRPC call in helm is here

https://github.com/kubernetes/helm/blob/master/pkg/helm/client.go#L67

if we can get that to work, then we can worry about the deploy with a chart. cc/ @kemcake

**Comment by sebgoa** [comment]
_From @kemcake on August 16, 2016 9:23_

DONE ✅ 🎉 🙀 Hooray! cc @runseb 
I managed to get a gRPC call working. I call `listReleases` and I get a response with a list of releases including `wobbly-lionfish` !
![screenshot 2016-08-16 11 22 37](https://cloud.githubusercontent.com/assets/4311124/17694365/cc91b35e-63a3-11e6-987c-b3219be66d01.png)

**Comment by sebgoa** [comment]
awesome...

**Comment by sebgoa** [comment]
so now to deploy a chart aka `installRelease` , the function is:

https://github.com/kubernetes/helm/blob/master/pkg/helm/client.go#L78

The new trick is that we have to load the chart in a struct using a load function from:

https://github.com/kubernetes/helm/blob/master/pkg/chartutil/load.go

So we need to download the actual tarball of the chart (form the index.yaml url), and load it in the appropriate structure to pass to `installRelease`.

the structure is defined in the proto definition, to generate a buffer for the gRPC call:

https://github.com/kubernetes/helm/blob/master/pkg/proto/hapi/chart/chart.pb.go

**Comment by sebgoa** [comment]
the index file format has changed to

```
apiVersion: v1
entries:
  alpine:
  - created: 2016-10-10T21:46:58.562869+02:00
    description: Simple pod running Alpine Linux.
    digest: dc3badf2bd2b103632af73ba645d5b355dd87c656cf8c047e9db524043d88741
    home: http://www.alpinelinux.org/
    keywords:
    - package
    - provides
    - basic
    - alpine
    - linux
    - image
    - used
    - basic
    - debugging
    - troubleshooting
    - default
    - starts
    - sleeps
    - long
    - time
    - eventually
    - stops
    name: alpine
    urls:
    - http://storage.googleapis.com/skippbox-charts/alpine-0.1.0.tgz
    version: 0.1.0
  cassandra:
  - created: 2016-10-10T21:46:58.563443+02:00
    description: The Apache Cassandra Project.
    digest: 5f64ab5e3f7827885b15c4502e3fbae252a774ba8519020d3af26055f504afe2
    home: http://cassandra.apache.org/
    keywords:
    - package
    - deploys
    - cassandra
    - kubernetes
    name: cassandra
    urls:
    - http://storage.googleapis.com/skippbox-charts/cassandra-0.2.1.tgz
    version: 0.2.1
```
