### ISSUE TITLE
Enable Browser open with LoadBalancer type service

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#49]
_From @sebgoa on August 11, 2016 10:12_

on k8s clusters where you can set service type to LoadBalancer, we should be able to open the browser on the LB IP.

flow:
- set LB service type
- After some time (not immediate), the Service gets a public IP in status.loadBalancer.ingress

```
status:
  loadBalancer:
    ingress:
    - ip: 130.211.61.16
```

we should be able to open the service on that IP like we do with NodePort.

_Copied from original issue: skippbox/cabin-sw#63_
